sonar.projectKey=Oleh-Creator_Rozklad
sonar.organization=oleh-creator
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,schedule.db,seed_data.py
sonar.tests=test_schedule.py
